'use client';

// AR Aging stacked bar chart
const AGING_BUCKETS = [
  { label: '0–30 days', value: 212, color: '#10b981' },
  { label: '31–60 days', value: 54, color: '#f59e0b' },
  { label: '61–90 days', value: 32, color: '#f97316' },
  { label: '90+ days', value: 14, color: '#ef4444' },
];

function AgingBar() {
  const total = AGING_BUCKETS.reduce((s, b) => s + b.value, 0);
  let left = 0;
  return (
    <div className="mt-3 flex flex-col gap-2">
      <div className="flex h-6 w-full rounded-md overflow-hidden border border-border">
        {AGING_BUCKETS.map((b, i) => {
          const pct = (b.value / total) * 100;
          const el = (
            <div
              key={i}
              className="h-full flex items-center justify-center text-[9px] font-semibold text-white"
              style={{ width: `${pct}%`, backgroundColor: b.color, opacity: 0.9, marginLeft: i === 0 ? 0 : 0 }}
              title={`${b.label}: $${b.value}K`}
            >
              {pct > 10 ? `$${b.value}K` : ''}
            </div>
          );
          left += pct;
          return el;
        })}
      </div>
      <div className="flex flex-wrap gap-3 text-[10px] text-mutedText">
        {AGING_BUCKETS.map((b) => (
          <span key={b.label} className="flex items-center gap-1">
            <span className="h-2 w-2 rounded-full" style={{ backgroundColor: b.color }} />
            {b.label} · <span className="font-mono text-bodyText">${b.value}K</span>
          </span>
        ))}
      </div>
    </div>
  );
}

export function ReportPreview() {
  return (
    <div className="flex flex-col gap-5">
      {/* Cover */}
      <div className="bg-navy/[0.03] border border-navy/10 rounded-lg px-5 py-4">
        <div className="flex items-start justify-between gap-3 flex-wrap">
          <div className="min-w-0">
            <p className="text-[10px] uppercase tracking-widest text-mutedText">Prism · Finance</p>
            <h4 className="text-base font-semibold text-navy mt-1">AR/AP Health Report · Q1 2026</h4>
            <p className="text-[11px] text-mutedText mt-1">
              Generated by Prism on Apr 18, 2026 · Jan 1 – Mar 31 · RevenuePoint Manufacturing
            </p>
          </div>
          <div className="flex items-center gap-2">
            <span className="text-[10px] font-semibold uppercase tracking-wider px-2 py-0.5 rounded border bg-emerald-50 text-emerald-700 border-emerald-200">
              Completed
            </span>
          </div>
        </div>
      </div>

      {/* Executive Summary */}
      <section>
        <p className="text-[10px] text-mutedText uppercase tracking-widest font-semibold mb-2">
          Executive Summary
        </p>
        <p className="text-[13px] leading-relaxed text-bodyText">
          AR balance closed Q1 at{' '}
          <span className="font-mono font-semibold text-navy">$312K</span>, up 14% QoQ
          against a sales volume increase of 9%. Aging profile remains healthy —{' '}
          <span className="font-mono font-semibold text-navy">68%</span> of balance is
          under 30 days — but three accounts account for{' '}
          <span className="font-mono font-semibold text-navy">54%</span> of the 60+ day
          overdue pool and warrant escalation this week.
        </p>
        <p className="mt-3 text-[13px] leading-relaxed text-bodyText">
          On the AP side, DPO held steady at 38 days (vs. 41 target). No vendor holds or
          late-fee exposures identified. Cash conversion cycle improved by 2.1 days vs. Q4.
        </p>
      </section>

      {/* Aging chart */}
      <section>
        <p className="text-[10px] text-mutedText uppercase tracking-widest font-semibold mb-2">
          AR Aging · $312K total
        </p>
        <AgingBar />
      </section>

      {/* Findings */}
      <section>
        <p className="text-[10px] text-mutedText uppercase tracking-widest font-semibold mb-2">
          Key Findings
        </p>
        <ul className="flex flex-col gap-2.5">
          {[
            {
              impact: 'High',
              impactClass: 'bg-red-50 text-red-700 border-red-200',
              body:
                'Meridian Builders holds 38% of the 60+ day overdue balance ($47.2K, 62 days). Recommend formal escalation and credit hold.',
            },
            {
              impact: 'Medium',
              impactClass: 'bg-amber-50 text-amber-700 border-amber-200',
              body:
                'Cascade Metals average DSO up 11 days vs prior quarter. Likely driver: leadership change on AP side.',
            },
            {
              impact: 'Low',
              impactClass: 'bg-emerald-50 text-emerald-700 border-emerald-200',
              body:
                'Pacific NW Construction prepaid $68K on the Q2 order. No action required; flagged for cash-flow forecast.',
            },
          ].map((f, i) => (
            <li key={i} className="flex gap-3">
              <span
                className={`text-[9px] font-semibold uppercase tracking-wider px-1.5 py-0.5 h-fit shrink-0 rounded border ${f.impactClass}`}
              >
                {f.impact}
              </span>
              <p className="text-[12px] leading-relaxed text-bodyText italic">{f.body}</p>
            </li>
          ))}
        </ul>
      </section>

      {/* Recommendations */}
      <section className="bg-offWhite border border-border rounded-lg p-4">
        <p className="text-[10px] text-mutedText uppercase tracking-widest font-semibold mb-2">
          Recommended Actions
        </p>
        <ol className="flex flex-col gap-2 text-[12px] text-bodyText list-decimal list-inside marker:text-crimson">
          <li>Dispatch collections outreach to Meridian Builders (scripted · template attached).</li>
          <li>Route a short check-in email to the new Cascade Metals AP lead to reset payment cadence.</li>
          <li>Lock current DPO target; no change to AP policy recommended this quarter.</li>
        </ol>
      </section>

      {/* Footer */}
      <div className="flex items-center justify-between pt-3 border-t border-border text-[10px] text-mutedText">
        <span>Generated by Prism · query cost $0.04 · sourced from Foundry warehouse</span>
        <span className="px-3 py-1 rounded border border-border bg-white text-bodyText font-medium">
          Download PDF
        </span>
      </div>
    </div>
  );
}
