import type { IndustryId } from '@/context/IndustryContext';

/* =========================================================================
 *  LENS PREVIEW CONTENT — per industry, per view type
 * =========================================================================
 *  Each industry provides specs for the four Lens view types:
 *    - dashboard (rich: header, KPIs, line chart, donut, horizontal bars)
 *    - report    (rich: cover, summary, chart, findings, recommendations)
 *    - metricTree (lightweight: root node label + status line)
 *    - map        (lightweight: title, item count, legend labels)
 */

/* -------------------------- Dashboard spec ------------------------------- */
export type DashboardKpi = {
  label: string;
  value: string;
  trend: string;
  trendGood: boolean;
  goal: string;
  status: 'on-track' | 'at-risk' | 'off-track';
  spark: number[];
};

export type DashboardLineSeries = {
  name: string;
  color: string;
  values: number[];
};

export type DashboardDonutSlice = {
  label: string;
  value: number;
  color: string;
};

export type DashboardHorizontalBar = {
  label: string;
  value: number;
};

export type DashboardSpec = {
  eyebrow: string; // e.g. "Harborline · Lens"
  title: string; // e.g. "Pharmacy Operations · Last 30 Days"
  kpis: DashboardKpi[]; // 3 KPI cards
  line: {
    title: string; // e.g. "Daily Script Volume · Last 30 Days"
    series: DashboardLineSeries[]; // 2-3 series
    goalReferencePct: number; // 0-1 vertical position of the goal dashed line
  };
  donut: {
    title: string; // e.g. "Scripts by Compound Type"
    slices: DashboardDonutSlice[];
    centerValue: string; // e.g. "2,847"
    centerSublabel: string; // e.g. "scripts / week"
  };
  horizontalBars: {
    title: string; // e.g. "Avg Turnaround by Location"
    bars: DashboardHorizontalBar[];
    max: number;
    goal: number;
    unit: string; // e.g. "h" or "%"
    goalLabel: string; // e.g. "goal 48h"
  };
};

/* ---------------------------- Report spec -------------------------------- */
export type ReportAgingBucket = {
  label: string;
  value: number; // relative magnitude
  color: string;
  display: string; // e.g. "$212K"
};

export type ReportFinding = {
  impact: 'High' | 'Medium' | 'Low';
  body: string;
};

export type ReportSpec = {
  category: string; // e.g. "Prism · Finance"
  title: string; // e.g. "AR/AP Health Report · Q1 2026"
  dateLine: string; // e.g. "Generated by Prism on Apr 24, 2026 · Jan 1 – Mar 31 · Vantage Industrial"
  status: 'Completed' | 'Generating';
  summary: string[]; // 2 paragraphs, first sentence gets emphasis
  chartTitle: string; // e.g. "AR Aging · $312K total"
  aging: ReportAgingBucket[];
  findings: ReportFinding[];
  recommendations: string[];
  footer: string; // e.g. "Generated by Prism · query cost $0.04 · sourced from Foundry warehouse"
};

/* ------------------------- Metric tree spec ------------------------------ */
export type MetricTreeSpec = {
  eyebrow: string; // e.g. "Vantage Industrial · Lens"
  title: string; // e.g. "North Star → Drivers"
  rootLabel: string; // top-level metric name — e.g. "Monthly Revenue"
  rootValue: string; // e.g. "$1.42M"
  subtitle: string; // one-liner description of the tree
};

/* ------------------------------ Map spec --------------------------------- */
export type MapSpec = {
  title: string; // e.g. "Customer Map · 15 locations"
  windowLabel: string; // e.g. "Last 30 Days"
  legendTitle: string; // e.g. "AR status"
  legendItems: { label: string; color: string }[];
};

export type IndustryLensContent = {
  dashboard: DashboardSpec;
  report: ReportSpec;
  metricTree: MetricTreeSpec;
  map: MapSpec;
};

/* =========================================================================
 *  PER-INDUSTRY CONTENT
 * ========================================================================= */
export const lensContentByIndustry: Record<IndustryId, IndustryLensContent> = {
  /* ----------------------------- Manufacturing ----------------------------- */
  manufacturing: {
    dashboard: {
      eyebrow: 'Vantage Industrial · Lens',
      title: 'Plant Operations · Last 30 Days',
      kpis: [
        {
          label: 'OEE Avg',
          value: '76.8%',
          trend: '-2.4pp',
          trendGood: false,
          goal: '≥ 80%',
          status: 'at-risk',
          spark: [81, 80.5, 80.2, 79.8, 79.4, 78.9, 78.4, 77.9, 77.5, 77.2, 77.0, 76.8],
        },
        {
          label: 'Scrap Rate',
          value: '2.3%',
          trend: '+0.4pp',
          trendGood: false,
          goal: '≤ 2.0%',
          status: 'off-track',
          spark: [1.9, 1.9, 2.0, 2.0, 2.1, 2.1, 2.2, 2.2, 2.2, 2.3, 2.3, 2.3],
        },
        {
          label: 'Throughput',
          value: '4.12M u',
          trend: '+3.0%',
          trendGood: true,
          goal: '4.00M u',
          status: 'on-track',
          spark: [3.92, 3.95, 3.98, 4.00, 4.02, 4.04, 4.06, 4.08, 4.10, 4.11, 4.12, 4.12],
        },
      ],
      line: {
        title: 'Daily OEE by line · Last 30 days',
        series: [
          { name: 'Line 1', color: '#2563eb', values: [82, 83, 82, 84, 82, 83, 85, 83, 84, 86, 84, 85] },
          { name: 'Line 2', color: '#059669', values: [84, 83, 82, 81, 78, 76, 74, 72, 71, 70, 69, 71] },
          { name: 'Line 3', color: '#d97706', values: [80, 81, 80, 82, 81, 80, 82, 81, 83, 82, 84, 84] },
        ],
        goalReferencePct: 0.18,
      },
      donut: {
        title: 'Throughput by SKU family',
        slices: [
          { label: 'Industrial Fasteners', value: 34, color: '#2563eb' },
          { label: 'Hydraulic Components', value: 22, color: '#059669' },
          { label: 'Safety Equipment', value: 18, color: '#d97706' },
          { label: 'Cutting Tools', value: 14, color: '#7c3aed' },
          { label: 'Raw Materials', value: 12, color: '#64748b' },
        ],
        centerValue: '4.12M',
        centerSublabel: 'units / month',
      },
      horizontalBars: {
        title: 'Scrap % by Line (target ≤ 2.0%)',
        bars: [
          { label: 'Line 1', value: 1.8 },
          { label: 'Line 2', value: 3.9 },
          { label: 'Line 3', value: 2.0 },
          { label: 'Packaging', value: 1.4 },
          { label: 'Finishing', value: 1.6 },
        ],
        max: 5,
        goal: 2.0,
        unit: '%',
        goalLabel: 'goal 2.0%',
      },
    },
    report: {
      category: 'Prism · Operations',
      title: 'Monthly Production Scorecard · March 2026',
      dateLine: 'Generated by Prism on Apr 24, 2026 · Mar 1 – Mar 31 · Vantage Industrial',
      status: 'Completed',
      summary: [
        'March OEE averaged 76.8% across three lines — off-target (≥80%). Line 2 carried most of the underperformance after a Mar 18 changeover that ran 47 minutes over spec and a lingering shift-3 scrap elevation.',
        'Throughput held steady at 4.1M units; revenue $4.12M (+3% MoM). The productivity hit was absorbed by unit mix, not top-line — but the compensating Q2 run of premium SKUs will not repeat, so OEE needs to recover.',
      ],
      chartTitle: 'OEE by line · Availability · Performance · Quality',
      aging: [
        { label: 'Line 1', value: 78, color: '#10b981', display: '78%' },
        { label: 'Line 2', value: 58, color: '#ef4444', display: '58%' },
        { label: 'Line 3', value: 72, color: '#f59e0b', display: '72%' },
      ],
      findings: [
        { impact: 'High', body: 'Line 2 Mar-18 changeover ran 47 min long; downstream scrap elevated for 3 shifts.' },
        { impact: 'High', body: 'T-204 upstream temp sensor drifting 4°C — correlates with scrap spike start.' },
        { impact: 'Low', body: 'Shift-3 cross-shift operators show 3.2× scrap vs steady-state team.' },
      ],
      recommendations: [
        'Schedule Line 2 preventive maintenance window this week.',
        'Replace T-204 sensor and add drift monitoring threshold.',
        'Refresher training for 2 cross-shift operators flagged by scrap correlation.',
      ],
      footer: 'Generated by Prism · query cost $0.09 · sourced from Foundry warehouse',
    },
    metricTree: {
      eyebrow: 'Vantage Industrial · Lens',
      title: 'Throughput → Drivers',
      rootLabel: 'Monthly Throughput',
      rootValue: '4.12M u',
      subtitle: 'Availability × Performance × Quality, broken down by line and shift.',
    },
    map: {
      title: 'Plant Fleet · 2 locations',
      windowLabel: 'Line Status · Live',
      legendTitle: 'Line status',
      legendItems: [
        { label: 'Running', color: '#10b981' },
        { label: 'Changeover', color: '#f59e0b' },
        { label: 'Halted', color: '#ef4444' },
        { label: 'Plant HQ', color: '#3b82f6' },
      ],
    },
  },

  /* -------------------------------- Pharmacy -------------------------------- */
  pharmacy: {
    dashboard: {
      eyebrow: 'Harborline · Lens',
      title: 'Pharmacy Operations · Last 30 Days',
      kpis: [
        {
          label: 'Scripts This Week',
          value: '2,847',
          trend: '+3.2%',
          trendGood: true,
          goal: '3,000',
          status: 'at-risk',
          spark: [2550, 2620, 2590, 2710, 2680, 2760, 2730, 2790, 2820, 2800, 2830, 2847],
        },
        {
          label: 'Backlog > 48h',
          value: '47',
          trend: '+12',
          trendGood: false,
          goal: '≤ 20',
          status: 'off-track',
          spark: [22, 24, 28, 25, 30, 32, 35, 38, 40, 42, 45, 47],
        },
        {
          label: 'On-Time Fill Rate',
          value: '91.4%',
          trend: '-2.1%',
          trendGood: false,
          goal: '≥ 95%',
          status: 'off-track',
          spark: [95.1, 94.8, 94.3, 94.1, 93.7, 93.2, 92.9, 92.5, 92.1, 91.8, 91.6, 91.4],
        },
      ],
      line: {
        title: 'Daily Script Volume · Last 30 Days',
        series: [
          { name: 'Downtown', color: '#2563eb', values: [108, 112, 105, 118, 120, 115, 122, 128, 125, 130, 135, 138] },
          { name: 'Westside', color: '#059669', values: [92, 95, 98, 96, 100, 102, 99, 104, 108, 106, 110, 112] },
          { name: 'Northgate', color: '#d97706', values: [84, 86, 82, 88, 85, 90, 88, 92, 95, 93, 97, 98] },
        ],
        goalReferencePct: 0.18,
      },
      donut: {
        title: 'Scripts by Compound Type',
        slices: [
          { label: 'Hormone', value: 34, color: '#2563eb' },
          { label: 'Pain Mgmt', value: 22, color: '#059669' },
          { label: 'Veterinary', value: 18, color: '#d97706' },
          { label: 'Dermatology', value: 14, color: '#7c3aed' },
          { label: 'Other', value: 12, color: '#64748b' },
        ],
        centerValue: '2,847',
        centerSublabel: 'scripts / week',
      },
      horizontalBars: {
        title: 'Avg Turnaround by Location',
        bars: [
          { label: 'Downtown', value: 44 },
          { label: 'Westside', value: 61 },
          { label: 'Northgate', value: 48 },
          { label: 'Lakeside', value: 42 },
          { label: 'Eastport', value: 46 },
        ],
        max: 72,
        goal: 48,
        unit: 'h',
        goalLabel: 'goal 48h',
      },
    },
    report: {
      category: 'Prism · Pharmacy',
      title: 'Daily Location Briefing · 2026-04-23',
      dateLine: 'Generated by Prism on Apr 24, 2026 · Prior day · Harborline (5 locations)',
      status: 'Completed',
      summary: [
        '268 scripts processed across 5 locations yesterday (+4% WoW). Westside remains the outlier at -18% vs prior week — Dr. Ramirez contribution fell to zero; outreach initiated.',
        'Compounding QC pass rate held 96.8%. One controlled-substance variance flagged at Westside (3-vial ketamine) — DEA 222 reported within the 24-hour window.',
      ],
      chartTitle: 'Rx volume by location · 268 total',
      aging: [
        { label: 'Downtown', value: 82, color: '#2563eb', display: '82' },
        { label: 'Lakeside', value: 58, color: '#059669', display: '58' },
        { label: 'Northgate', value: 52, color: '#d97706', display: '52' },
        { label: 'Eastport', value: 44, color: '#7c3aed', display: '44' },
        { label: 'Westside', value: 32, color: '#ef4444', display: '32' },
      ],
      findings: [
        { impact: 'High', body: 'Westside volume down 18% WoW — Dr. Ramirez zero contribution for 8 consecutive days.' },
        { impact: 'Medium', body: 'Afternoon compounding team at Westside is 1 short all week; turnaround +4h there.' },
        { impact: 'Low', body: 'Downtown leading location performance; capacity headroom ~18%.' },
      ],
      recommendations: [
        'Execute Dr. Ramirez outreach sequence (drafted by Otto).',
        'Approve temporary shift-3 compounding reinforcement at Westside for this week.',
        'Run Prism · Location Health weekly until Westside recovers.',
      ],
      footer: 'Generated by Prism · query cost $0.04 · sourced from Foundry warehouse',
    },
    metricTree: {
      eyebrow: 'Harborline · Lens',
      title: 'Rx Volume → Drivers',
      rootLabel: 'Weekly Scripts',
      rootValue: '2,847',
      subtitle: 'Intake × Compounding × QC × Delivery, broken down by location and shift.',
    },
    map: {
      title: 'Pharmacy Locations · 5 sites',
      windowLabel: 'Location Status · Today',
      legendTitle: 'Location status',
      legendItems: [
        { label: 'On target', color: '#10b981' },
        { label: 'Turnaround alert', color: '#f59e0b' },
        { label: 'QC variance', color: '#ef4444' },
        { label: 'HQ · Portland', color: '#3b82f6' },
      ],
    },
  },

  /* ------------------------------ Distribution ----------------------------- */
  distribution: {
    dashboard: {
      eyebrow: 'Cascade Industrial · Lens',
      title: 'Sales & Warehouse · Last 30 Days',
      kpis: [
        {
          label: 'Open Pipeline',
          value: '$14.2M',
          trend: '+6%',
          trendGood: true,
          goal: '$14.0M',
          status: 'on-track',
          spark: [12.8, 13.0, 13.1, 13.4, 13.6, 13.7, 13.8, 13.9, 14.0, 14.1, 14.1, 14.2],
        },
        {
          label: 'Fill Rate',
          value: '96.2%',
          trend: '-0.8pp',
          trendGood: false,
          goal: '≥ 97%',
          status: 'at-risk',
          spark: [97.4, 97.2, 97.1, 96.9, 96.8, 96.8, 96.6, 96.5, 96.4, 96.3, 96.2, 96.2],
        },
        {
          label: 'AR Days',
          value: '37 d',
          trend: '-2 d',
          trendGood: true,
          goal: '≤ 42',
          status: 'on-track',
          spark: [41, 40, 40, 39, 39, 38, 38, 38, 37, 37, 37, 37],
        },
      ],
      line: {
        title: 'Weekly Rep Pipeline Build · Last 12 weeks ($M)',
        series: [
          { name: 'West', color: '#2563eb', values: [3.2, 3.3, 3.5, 3.6, 3.6, 3.8, 3.9, 4.0, 4.2, 4.3, 4.4, 4.6] },
          { name: 'NW', color: '#059669', values: [2.8, 2.9, 3.0, 3.1, 3.2, 3.2, 3.3, 3.4, 3.5, 3.5, 3.6, 3.8] },
          { name: 'East', color: '#d97706', values: [3.8, 3.6, 3.4, 3.3, 3.3, 3.2, 3.1, 3.0, 3.0, 2.9, 2.9, 2.8] },
        ],
        goalReferencePct: 0.3,
      },
      donut: {
        title: 'Revenue by Customer Segment',
        slices: [
          { label: 'Construction', value: 36, color: '#2563eb' },
          { label: 'Fabrication', value: 24, color: '#059669' },
          { label: 'Mining', value: 18, color: '#d97706' },
          { label: 'Logistics', value: 12, color: '#7c3aed' },
          { label: 'Other', value: 10, color: '#64748b' },
        ],
        centerValue: '$48M',
        centerSublabel: 'revenue / year',
      },
      horizontalBars: {
        title: 'Fill Rate by DC (target 97%)',
        bars: [
          { label: 'Seattle', value: 98.4 },
          { label: 'Portland', value: 96.8 },
          { label: 'Tacoma', value: 87.0 },
          { label: 'Spokane', value: 94.2 },
          { label: 'Boise', value: 95.6 },
        ],
        max: 100,
        goal: 97,
        unit: '%',
        goalLabel: 'goal 97%',
      },
    },
    report: {
      category: 'Prism · Sales & CRM',
      title: 'Weekly Pipeline Health · Week of Apr 21, 2026',
      dateLine: 'Generated by Prism on Apr 24, 2026 · Week of Apr 21 · Cascade Industrial',
      status: 'Completed',
      summary: [
        '$14.2M open pipeline across 47 reps. Velocity up 12% WoW; win-rate steady at 33%. 7 stalled deals (>14 days) in Negotiation — $2.1M at risk of slipping to Q3.',
        'Customer-concentration flag: top 10 accounts represent 38% of open pipeline. No single at-risk account larger than $340K.',
      ],
      chartTitle: 'Pipeline by stage · $14.2M',
      aging: [
        { label: 'Qualification', value: 2400, color: '#60a5fa', display: '$2.4M' },
        { label: 'Proposal', value: 4600, color: '#3b82f6', display: '$4.6M' },
        { label: 'Negotiation', value: 5200, color: '#1d4ed8', display: '$5.2M' },
        { label: 'Verbal', value: 1400, color: '#065f46', display: '$1.4M' },
        { label: 'Legal', value: 600, color: '#10b981', display: '$0.6M' },
      ],
      findings: [
        { impact: 'High', body: '7 Negotiation deals stalled >14 days — concentrated in 3 reps; coachable pattern.' },
        { impact: 'Medium', body: 'Territory NE lags pipeline addition by 18%; discovery pipeline thin.' },
        { impact: 'Low', body: 'Velocity gain is healthy — conversion from Proposal → Negotiation has sped up.' },
      ],
      recommendations: [
        'Stalled-deal blitz: 30-min partner review per deal by Wednesday.',
        'Lead-gen refresh for NE territory (list + outbound sequence) starting Monday.',
        'Continue coaching 3 reps on Negotiation-stage time compression.',
      ],
      footer: 'Generated by Prism · query cost $0.05 · sourced from Foundry warehouse',
    },
    metricTree: {
      eyebrow: 'Cascade Industrial · Lens',
      title: 'Revenue → Drivers',
      rootLabel: 'Monthly Revenue',
      rootValue: '$4.0M',
      subtitle: 'Orders × AOV × Reorder Rate, broken down by territory and customer segment.',
    },
    map: {
      title: 'Customer Map · 220 accounts',
      windowLabel: 'Last 30 days',
      legendTitle: 'AR status',
      legendItems: [
        { label: 'Current', color: '#10b981' },
        { label: '30-60d overdue', color: '#f59e0b' },
        { label: '60+d / Credit Hold', color: '#ef4444' },
        { label: 'Distribution Center', color: '#3b82f6' },
      ],
    },
  },

  /* ------------------------------- Nonprofit ------------------------------- */
  nonprofit: {
    dashboard: {
      eyebrow: 'Horizon Nonprofit · Lens',
      title: 'Fundraising & Programs · YTD',
      kpis: [
        {
          label: 'YTD Revenue',
          value: '$3.4M',
          trend: '+7% YoY',
          trendGood: true,
          goal: '$12M annual',
          status: 'on-track',
          spark: [0.6, 1.1, 1.6, 2.0, 2.4, 2.7, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4],
        },
        {
          label: 'Donor Retention',
          value: '64%',
          trend: '-7pp',
          trendGood: false,
          goal: '≥ 70%',
          status: 'off-track',
          spark: [71, 71, 70, 69, 69, 68, 67, 66, 66, 65, 64, 64],
        },
        {
          label: 'Program Exp. Ratio',
          value: '82.4%',
          trend: 'stable',
          trendGood: true,
          goal: '≥ 80%',
          status: 'on-track',
          spark: [82, 82.4, 82.2, 82.6, 82.4, 82.5, 82.4, 82.5, 82.4, 82.5, 82.4, 82.4],
        },
      ],
      line: {
        title: 'Cumulative Fundraising · YTD ($M)',
        series: [
          { name: 'This year', color: '#2563eb', values: [0.4, 0.8, 1.2, 1.6, 2.1, 2.4, 2.7, 2.9, 3.0, 3.2, 3.3, 3.4] },
          { name: 'Last year', color: '#94a3b8', values: [0.4, 0.7, 1.1, 1.5, 1.9, 2.2, 2.5, 2.7, 2.9, 3.0, 3.1, 3.2] },
        ],
        goalReferencePct: 0.25,
      },
      donut: {
        title: 'Revenue by Source',
        slices: [
          { label: 'Major gifts', value: 40, color: '#2563eb' },
          { label: 'Grants', value: 28, color: '#059669' },
          { label: 'Monthly giving', value: 14, color: '#d97706' },
          { label: 'Events', value: 12, color: '#7c3aed' },
          { label: 'Online', value: 6, color: '#64748b' },
        ],
        centerValue: '$3.4M',
        centerSublabel: 'YTD revenue',
      },
      horizontalBars: {
        title: 'Program Outcome Achievement (% of target)',
        bars: [
          { label: 'Youth', value: 118 },
          { label: 'Food', value: 104 },
          { label: 'Job Training', value: 96 },
          { label: 'Rural Outreach', value: 66 },
          { label: 'Admin', value: 100 },
        ],
        max: 140,
        goal: 100,
        unit: '%',
        goalLabel: 'goal 100%',
      },
    },
    report: {
      category: 'Prism · Fundraising',
      title: 'Quarterly Board Packet · Q1 2026',
      dateLine: 'Generated by Prism on Apr 23, 2026 · Q1 2026 · Horizon Nonprofit',
      status: 'Completed',
      summary: [
        'Q1 total revenue $3.4M (+7% YoY) against $12M annual goal (pace 113% at quarter-mark). Program expenses ratio held at 82.4%. 3 programs exceeded outcome targets; 1 is trending below and under active redesign.',
        'Donor retention is the yellow flag: 64% vs 71% prior year. Lapsed-donor cohort is largely 6-12 months — recoverable with a disciplined Q2 win-back campaign.',
      ],
      chartTitle: 'Q1 revenue mix · $3.4M',
      aging: [
        { label: 'Major gifts', value: 1360, color: '#2563eb', display: '$1.36M' },
        { label: 'Grants', value: 952, color: '#059669', display: '$952K' },
        { label: 'Monthly', value: 476, color: '#d97706', display: '$476K' },
        { label: 'Events', value: 408, color: '#7c3aed', display: '$408K' },
        { label: 'Online', value: 204, color: '#64748b', display: '$204K' },
      ],
      findings: [
        { impact: 'High', body: 'Major-gifts pipeline is outperforming plan; hold cadence and add 2 cultivation events in Q2.' },
        { impact: 'Medium', body: 'Lapsed-donor cohort ($120K Q1 drag) is 80% recoverable with targeted win-back.' },
        { impact: 'Medium', body: 'Program 4 (rural outreach) outcomes below target — redesign approved, launch in Q2.' },
      ],
      recommendations: [
        'Launch 6-week lapsed-donor win-back campaign starting May 6.',
        'Schedule 2 major-gifts cultivation dinners in Q2 (CEO + board chair).',
        'Present Q1 narrative to board with program 4 redesign roadmap.',
      ],
      footer: 'Generated by Prism · query cost $0.09 · sourced from Foundry warehouse',
    },
    metricTree: {
      eyebrow: 'Horizon Nonprofit · Lens',
      title: 'Revenue → Drivers',
      rootLabel: 'YTD Revenue',
      rootValue: '$3.4M',
      subtitle: 'Acquisition × Retention × Upgrade across donor tiers and campaign channels.',
    },
    map: {
      title: 'Chapter / Service Area Map · 12 chapters',
      windowLabel: 'Program outcomes YTD',
      legendTitle: 'Chapter status',
      legendItems: [
        { label: 'On target', color: '#10b981' },
        { label: 'Monitoring', color: '#f59e0b' },
        { label: 'Behind plan', color: '#ef4444' },
        { label: 'National HQ', color: '#3b82f6' },
      ],
    },
  },

  /* ------------------------------- Healthcare ------------------------------ */
  healthcare: {
    dashboard: {
      eyebrow: 'Valley Ambulatory · Lens',
      title: 'Revenue Cycle · Last 30 Days',
      kpis: [
        {
          label: 'Net Collection Rate',
          value: '85.2%',
          trend: '-1.8pp',
          trendGood: false,
          goal: '≥ 90%',
          status: 'off-track',
          spark: [87.4, 87.1, 86.8, 86.4, 86.0, 85.8, 85.6, 85.5, 85.4, 85.3, 85.2, 85.2],
        },
        {
          label: 'Denial Rate',
          value: '7.4%',
          trend: '+0.9pp',
          trendGood: false,
          goal: '≤ 5.0%',
          status: 'off-track',
          spark: [6.2, 6.4, 6.5, 6.6, 6.8, 7.0, 7.1, 7.2, 7.3, 7.3, 7.4, 7.4],
        },
        {
          label: 'Days in AR',
          value: '38 d',
          trend: '+2 d',
          trendGood: false,
          goal: '≤ 35',
          status: 'at-risk',
          spark: [34, 35, 35, 36, 36, 37, 37, 37, 37, 38, 38, 38],
        },
      ],
      line: {
        title: 'Daily Charges & Collections · Last 30 days ($K)',
        series: [
          { name: 'Charges', color: '#2563eb', values: [268, 278, 282, 288, 290, 282, 298, 306, 302, 298, 306, 312] },
          { name: 'Collections', color: '#059669', values: [224, 232, 238, 240, 244, 238, 248, 254, 252, 250, 256, 260] },
        ],
        goalReferencePct: 0.28,
      },
      donut: {
        title: 'Payer Mix',
        slices: [
          { label: 'Medicare', value: 34, color: '#2563eb' },
          { label: 'BCBS', value: 22, color: '#059669' },
          { label: 'Aetna', value: 18, color: '#d97706' },
          { label: 'United', value: 14, color: '#7c3aed' },
          { label: 'Other', value: 12, color: '#64748b' },
        ],
        centerValue: '$8.4M',
        centerSublabel: 'charges / month',
      },
      horizontalBars: {
        title: 'Cost per Visit by Location (target $132)',
        bars: [
          { label: 'Scottsdale', value: 168 },
          { label: 'Phoenix', value: 118 },
          { label: 'Tempe', value: 138 },
          { label: 'Mesa', value: 132 },
          { label: 'Chandler', value: 140 },
        ],
        max: 200,
        goal: 132,
        unit: '$',
        goalLabel: 'goal $132',
      },
    },
    report: {
      category: 'Prism · Revenue Cycle',
      title: 'Monthly Revenue Cycle Report · March 2026',
      dateLine: 'Generated by Prism on Apr 23, 2026 · Mar 1 – Mar 31 · Valley Ambulatory',
      status: 'Completed',
      summary: [
        'March charges $8.42M; net collections $7.18M (net collection rate 85.2%, down 1.8 pts). Scottsdale denial spike drove most of the gap — $218K in Aetna denials with 62% recoverable through appeals.',
        'Patient balances 120+ days grew to $142K (+$28K MoM). Patient-financing program uptake is 14% vs 22% plan — needs stronger payment-plan offer at point of service.',
      ],
      chartTitle: 'AR aging · $3.8M total',
      aging: [
        { label: '0-30 days', value: 2842, color: '#10b981', display: '$2.84M' },
        { label: '31-60 days', value: 520, color: '#f59e0b', display: '$520K' },
        { label: '61-90 days', value: 296, color: '#f97316', display: '$296K' },
        { label: '91-120 days', value: 142, color: '#ef4444', display: '$142K' },
      ],
      findings: [
        { impact: 'High', body: 'Scottsdale Aetna denials CARC 97/204 — $218K; 62% recoverable through batch appeals.' },
        { impact: 'Medium', body: 'Patient-financing program uptake is the lowest it has been in 12 months.' },
        { impact: 'Low', body: 'Medicare collections remain steady; commercial is where the noise is.' },
      ],
      recommendations: [
        'Submit 34-claim Aetna appeal batch this week (pre-populated).',
        'Payment-plan offer script retraining at point of service, 8 locations.',
        'Escalate 120+ day balances to collections in tranches.',
      ],
      footer: 'Generated by Prism · query cost $0.08 · sourced from Foundry warehouse',
    },
    metricTree: {
      eyebrow: 'Valley Ambulatory · Lens',
      title: 'Net Collections → Drivers',
      rootLabel: 'Net Collections',
      rootValue: '$7.18M',
      subtitle: 'Clean Claims × Denial Recovery × AR Turns, broken down by location and payer.',
    },
    map: {
      title: 'Location Map · 8 clinics',
      windowLabel: 'Volume vs capacity · This week',
      legendTitle: 'Capacity',
      legendItems: [
        { label: 'On target', color: '#10b981' },
        { label: 'Under (<80%)', color: '#3b82f6' },
        { label: 'Over (>120%)', color: '#ef4444' },
        { label: 'Administrative HQ', color: '#64748b' },
      ],
    },
  },

  /* -------------------------- Property Management -------------------------- */
  propertyManagement: {
    dashboard: {
      eyebrow: 'Rivercrest Properties · Lens',
      title: 'Portfolio Performance · YTD',
      kpis: [
        {
          label: 'Occupancy',
          value: '94.8%',
          trend: '-0.2pp',
          trendGood: false,
          goal: '≥ 95%',
          status: 'at-risk',
          spark: [95.1, 95.0, 95.0, 94.9, 94.9, 94.8, 94.8, 94.8, 94.8, 94.8, 94.8, 94.8],
        },
        {
          label: 'Portfolio NOI',
          value: '$4.92M',
          trend: '-5.8% vs plan',
          trendGood: false,
          goal: '$5.22M',
          status: 'off-track',
          spark: [5.22, 5.18, 5.14, 5.10, 5.06, 5.02, 4.98, 4.96, 4.94, 4.92, 4.92, 4.92],
        },
        {
          label: 'Delinquency',
          value: '$182K',
          trend: '+$18K',
          trendGood: false,
          goal: '≤ $160K',
          status: 'at-risk',
          spark: [148, 152, 158, 162, 166, 170, 172, 176, 178, 180, 182, 182],
        },
      ],
      line: {
        title: 'Monthly Collections vs Plan · YTD ($M)',
        series: [
          { name: 'Actual', color: '#2563eb', values: [1.62, 1.64, 1.66, 1.64, 1.68, 1.70, 1.68, 1.72, 1.74, 1.72, 1.76, 1.78] },
          { name: 'Plan', color: '#94a3b8', values: [1.66, 1.68, 1.70, 1.70, 1.72, 1.74, 1.74, 1.76, 1.78, 1.78, 1.80, 1.82] },
        ],
        goalReferencePct: 0.28,
      },
      donut: {
        title: 'Portfolio Mix by Unit Count',
        slices: [
          { label: 'Class A', value: 36, color: '#2563eb' },
          { label: 'Class B', value: 42, color: '#059669' },
          { label: 'Workforce', value: 14, color: '#d97706' },
          { label: 'Senior', value: 8, color: '#7c3aed' },
        ],
        centerValue: '1,200',
        centerSublabel: 'units / 14 props',
      },
      horizontalBars: {
        title: 'Maintenance $/unit by property (target $186)',
        bars: [
          { label: 'Riverside', value: 412 },
          { label: 'Fairview', value: 228 },
          { label: 'Parkside', value: 198 },
          { label: 'Lakeside', value: 188 },
          { label: 'Cedar Park', value: 172 },
        ],
        max: 500,
        goal: 186,
        unit: '$',
        goalLabel: 'goal $186',
      },
    },
    report: {
      category: 'Prism · Finance',
      title: 'Monthly Ownership Package · March 2026',
      dateLine: 'Generated by Prism on Apr 23, 2026 · Mar 1 – Mar 31 · Rivercrest Properties',
      status: 'Completed',
      summary: [
        'Portfolio NOI $4.92M — 94.2% of plan. Four properties underperformed underwriting (Riverside, Fairview, Lakeside, Parkside). Riverside is the biggest drag ($162K NOI gap) — traced to elevator capex.',
        'Portfolio occupancy 94.8% — on plan. Fairview Tower has a 14-unit vacancy block currently being leased up; expected closure end of Q2.',
      ],
      chartTitle: 'NOI gap by property ($K)',
      aging: [
        { label: 'Riverside', value: 162, color: '#ef4444', display: '-$162K' },
        { label: 'Fairview', value: 92, color: '#f97316', display: '-$92K' },
        { label: 'Lakeside', value: 58, color: '#f59e0b', display: '-$58K' },
        { label: 'Parkside', value: 36, color: '#fbbf24', display: '-$36K' },
        { label: 'Others (net)', value: 140, color: '#10b981', display: '+$140K' },
      ],
      findings: [
        { impact: 'High', body: 'Riverside elevator issue is isolated to 2 buildings; full modernization at $180K has a 3-year ROI.' },
        { impact: 'Medium', body: 'Fairview vacancy block is structural (corporate-tenant move); lease-up plan in motion.' },
        { impact: 'Low', body: '10 of 14 properties are on or above plan — portfolio discipline is intact.' },
      ],
      recommendations: [
        'Approve Riverside-B elevator modernization capex.',
        'Expedite Fairview Tower lease-up with $5K/mo leasing bonus for next 60 days.',
        'Revise FY2026 capex reserve upward by $180K for elevator program.',
      ],
      footer: 'Generated by Prism · query cost $0.09 · sourced from Foundry warehouse',
    },
    metricTree: {
      eyebrow: 'Rivercrest Properties · Lens',
      title: 'NOI → Drivers',
      rootLabel: 'Portfolio NOI',
      rootValue: '$4.92M',
      subtitle: 'Revenue × Opex, broken down by property and unit class.',
    },
    map: {
      title: 'Portfolio Map · 14 properties',
      windowLabel: 'NOI vs plan · March',
      legendTitle: 'Property status',
      legendItems: [
        { label: 'On/above plan', color: '#10b981' },
        { label: 'Monitoring', color: '#f59e0b' },
        { label: 'Below plan', color: '#ef4444' },
        { label: 'Regional HQ', color: '#3b82f6' },
      ],
    },
  },

  /* ------------------------ Professional Services ------------------------ */
  professionalServices: {
    dashboard: {
      eyebrow: 'Meridian Consulting · Lens',
      title: 'Firm Performance · Last 30 Days',
      kpis: [
        {
          label: 'Utilization',
          value: '71.4%',
          trend: '-1.8pp',
          trendGood: false,
          goal: '≥ 75%',
          status: 'at-risk',
          spark: [74.2, 73.8, 73.4, 73.0, 72.8, 72.4, 72.0, 71.8, 71.6, 71.5, 71.4, 71.4],
        },
        {
          label: 'Engagement Margin',
          value: '38.2%',
          trend: '+0.6pp',
          trendGood: true,
          goal: '≥ 38%',
          status: 'on-track',
          spark: [37.2, 37.4, 37.5, 37.7, 37.8, 37.9, 38.0, 38.1, 38.1, 38.2, 38.2, 38.2],
        },
        {
          label: 'WIP 90+ days',
          value: '$186K',
          trend: '+$22K',
          trendGood: false,
          goal: '≤ $150K',
          status: 'off-track',
          spark: [148, 152, 158, 162, 166, 168, 172, 176, 178, 180, 184, 186],
        },
      ],
      line: {
        title: 'Weekly Utilization by Practice · 12 weeks (%)',
        series: [
          { name: 'Strategy', color: '#2563eb', values: [74, 75, 75, 74, 76, 76, 75, 77, 76, 77, 76, 76] },
          { name: 'Tech', color: '#059669', values: [72, 73, 74, 74, 75, 74, 73, 75, 74, 74, 74, 74] },
          { name: 'Fin Advisory', color: '#d97706', values: [72, 70, 69, 68, 68, 67, 67, 66, 66, 66, 66, 66] },
        ],
        goalReferencePct: 0.2,
      },
      donut: {
        title: 'Revenue by Practice',
        slices: [
          { label: 'Strategy', value: 32, color: '#2563eb' },
          { label: 'Technology', value: 28, color: '#059669' },
          { label: 'Fin Advisory', value: 20, color: '#d97706' },
          { label: 'M&A', value: 14, color: '#7c3aed' },
          { label: 'Tax', value: 6, color: '#64748b' },
        ],
        centerValue: '$84M',
        centerSublabel: 'revenue / year',
      },
      horizontalBars: {
        title: 'Engagement Margin by Practice (target 38%)',
        bars: [
          { label: 'Strategy', value: 42 },
          { label: 'Fin Advisory', value: 34 },
          { label: 'Technology', value: 40 },
          { label: 'M&A', value: 38 },
          { label: 'Tax', value: 36 },
        ],
        max: 50,
        goal: 38,
        unit: '%',
        goalLabel: 'goal 38%',
      },
    },
    report: {
      category: 'Prism · Finance',
      title: 'Weekly Partner Briefing · Week of Apr 21',
      dateLine: 'Generated by Prism on Apr 24, 2026 · Week of Apr 21 · Meridian Consulting',
      status: 'Completed',
      summary: [
        'Firm-wide utilization 71.4% (−1.8 pts vs target). Strategy and Technology practices at or above plan; Financial Advisory trailing at 66%.',
        '6 engagements at risk of budget overrun ($342K projected). Hartford M&A is the single biggest exposure — early-warning already issued this week.',
      ],
      chartTitle: 'Engagement overrun risk ($K)',
      aging: [
        { label: 'Hartford M&A', value: 96, color: '#ef4444', display: '+$96K' },
        { label: 'Summit Redesign', value: 78, color: '#f97316', display: '+$78K' },
        { label: 'Parker ERP', value: 64, color: '#f59e0b', display: '+$64K' },
        { label: 'Riverside Plan', value: 42, color: '#fbbf24', display: '+$42K' },
        { label: 'Cascade SCM', value: 38, color: '#fbbf24', display: '+$38K' },
        { label: 'Northgate Tax', value: 24, color: '#fde047', display: '+$24K' },
      ],
      findings: [
        { impact: 'High', body: 'Financial Advisory utilization shortfall = $340K annualized revenue impact if not corrected.' },
        { impact: 'Medium', body: '6 engagements concentrate in 3 PMs — coaching opportunity on scope management.' },
        { impact: 'Low', body: 'Engagement margin is holding despite utilization pressure — pricing discipline is good.' },
      ],
      recommendations: [
        'Reassign 2 FA partners to open Parker Industrial ERP engagement (immediate utilization fix).',
        'Scope-management workshop for 3 at-risk-engagement PMs in May.',
        'Lock pricing discipline into 2026 SOW templates firm-wide.',
      ],
      footer: 'Generated by Prism · query cost $0.07 · sourced from Foundry warehouse',
    },
    metricTree: {
      eyebrow: 'Meridian Consulting · Lens',
      title: 'EBITDA → Drivers',
      rootLabel: 'EBITDA',
      rootValue: '$21M',
      subtitle: 'Billable Utilization × Realization × Overhead, broken down by practice and office.',
    },
    map: {
      title: 'Office Performance · 12 offices',
      windowLabel: 'Utilization · YTD',
      legendTitle: 'Office status',
      legendItems: [
        { label: 'On target', color: '#10b981' },
        { label: 'Monitoring', color: '#f59e0b' },
        { label: 'Below plan', color: '#ef4444' },
        { label: 'Headquarters', color: '#3b82f6' },
      ],
    },
  },

  /* ------------------------- Financial Services -------------------------- */
  financialServices: {
    dashboard: {
      eyebrow: 'Legacy Advisors · Lens',
      title: 'Firm & Client Health · Q1',
      kpis: [
        {
          label: 'Firm AUM',
          value: '$2.12B',
          trend: '+4.2% QoQ',
          trendGood: true,
          goal: '$2.15B',
          status: 'at-risk',
          spark: [2.03, 2.04, 2.05, 2.06, 2.07, 2.08, 2.09, 2.10, 2.11, 2.11, 2.12, 2.12],
        },
        {
          label: 'Review Completion',
          value: '84%',
          trend: '-2pp',
          trendGood: false,
          goal: '≥ 95%',
          status: 'off-track',
          spark: [88, 88, 87, 86, 86, 85, 85, 85, 84, 84, 84, 84],
        },
        {
          label: 'Net New Assets',
          value: '$58M',
          trend: '+12% QoQ',
          trendGood: true,
          goal: '$50M',
          status: 'on-track',
          spark: [42, 44, 46, 48, 50, 52, 53, 54, 55, 56, 57, 58],
        },
      ],
      line: {
        title: 'AUM by Advisor · Top 5 (bn)',
        series: [
          { name: 'Kim', color: '#2563eb', values: [0.22, 0.22, 0.23, 0.24, 0.24, 0.25, 0.25, 0.26, 0.26, 0.27, 0.27, 0.28] },
          { name: 'Chen', color: '#059669', values: [0.18, 0.18, 0.19, 0.19, 0.20, 0.20, 0.21, 0.21, 0.22, 0.22, 0.23, 0.23] },
          { name: 'Patel', color: '#d97706', values: [0.16, 0.16, 0.17, 0.17, 0.18, 0.18, 0.19, 0.19, 0.20, 0.20, 0.21, 0.21] },
        ],
        goalReferencePct: 0.3,
      },
      donut: {
        title: 'AUM by Asset Class',
        slices: [
          { label: 'Equity', value: 52, color: '#2563eb' },
          { label: 'Fixed income', value: 30, color: '#059669' },
          { label: 'Alts', value: 10, color: '#d97706' },
          { label: 'Cash', value: 8, color: '#64748b' },
        ],
        centerValue: '$2.12B',
        centerSublabel: 'firm AUM',
      },
      horizontalBars: {
        title: 'Review Completion by Advisor (top 5, target 95%)',
        bars: [
          { label: 'Chen', value: 96 },
          { label: 'Patel', value: 92 },
          { label: 'Kim', value: 88 },
          { label: 'Hoffman', value: 68 },
          { label: 'Lin', value: 62 },
        ],
        max: 100,
        goal: 95,
        unit: '%',
        goalLabel: 'goal 95%',
      },
    },
    report: {
      category: 'Prism · Advisory',
      title: 'Advisor Book-of-Business Health · Q1 2026',
      dateLine: 'Generated by Prism on Apr 23, 2026 · Q1 2026 · Legacy Advisors',
      status: 'Completed',
      summary: [
        'Firm AUM $2.12B (+4.2% Q1). Client review completion 84% — trailing 2026 goal of 95%. 7 advisors at or above 95%; 3 below 70%.',
        'Client engagement score held at 82 (out of 100). 14 clients flagged as at-risk (portfolio drift + low engagement); concentrated in 4 advisor books.',
      ],
      chartTitle: 'AUM by advisor (top 8, $M)',
      aging: [
        { label: 'Kim', value: 280, color: '#2563eb', display: '$280M' },
        { label: 'Chen', value: 230, color: '#3b82f6', display: '$230M' },
        { label: 'Patel', value: 210, color: '#60a5fa', display: '$210M' },
        { label: 'Hoffman', value: 190, color: '#93c5fd', display: '$190M' },
        { label: 'Lin', value: 160, color: '#bfdbfe', display: '$160M' },
      ],
      findings: [
        { impact: 'High', body: '3 advisors below 70% review completion; AUM concentrated in their books = $340M at risk.' },
        { impact: 'Medium', body: '14 at-risk clients trace to portfolio-drift breaches + >9-month no-contact combinations.' },
        { impact: 'Low', body: 'Net new assets momentum is healthy — advisor-recruited referrals up 18% YoY.' },
      ],
      recommendations: [
        'Review-completion intervention for 3 advisors (scheduling assistant + pipeline review).',
        'Immediate outreach on 14 at-risk clients with pre-populated agendas.',
        'Double down on the referral program — strong Q1 signal.',
      ],
      footer: 'Generated by Prism · query cost $0.08 · sourced from Foundry warehouse',
    },
    metricTree: {
      eyebrow: 'Legacy Advisors · Lens',
      title: 'AUM → Drivers',
      rootLabel: 'Firm AUM',
      rootValue: '$2.12B',
      subtitle: 'Net New × Market × Attrition, broken down by advisor and office.',
    },
    map: {
      title: 'Advisor Territory Map · 6 offices',
      windowLabel: 'Net new assets · Q1',
      legendTitle: 'Office status',
      legendItems: [
        { label: 'Above plan', color: '#10b981' },
        { label: 'On plan', color: '#3b82f6' },
        { label: 'Below plan', color: '#ef4444' },
        { label: 'Headquarters', color: '#64748b' },
      ],
    },
  },

  /* -------------------------- Food & Beverage --------------------------- */
  foodBeverage: {
    dashboard: {
      eyebrow: 'Greenfield Roasting · Lens',
      title: 'Production & Margin · Last 30 Days',
      kpis: [
        {
          label: 'Gross Margin',
          value: '38.2%',
          trend: '-3.4pp',
          trendGood: false,
          goal: '≥ 41%',
          status: 'off-track',
          spark: [41.4, 41.0, 40.8, 40.4, 40.0, 39.6, 39.2, 38.9, 38.6, 38.4, 38.2, 38.2],
        },
        {
          label: 'Yield',
          value: '94.1%',
          trend: '-0.9pp',
          trendGood: false,
          goal: '≥ 95%',
          status: 'at-risk',
          spark: [95.1, 95.0, 94.9, 94.8, 94.7, 94.6, 94.5, 94.3, 94.2, 94.1, 94.1, 94.1],
        },
        {
          label: 'Spoilage',
          value: '$18K',
          trend: '+$4K',
          trendGood: false,
          goal: '≤ $14K',
          status: 'at-risk',
          spark: [12, 12.5, 13, 13.5, 14, 14.5, 15, 15.5, 16, 17, 18, 18],
        },
      ],
      line: {
        title: 'Daily Yield by Facility · Last 30 days (%)',
        series: [
          { name: 'Portland', color: '#2563eb', values: [94.1, 93.9, 93.7, 93.4, 93.2, 93.0, 92.9, 92.9, 92.8, 92.8, 92.8, 92.8] },
          { name: 'Tacoma', color: '#059669', values: [94.9, 94.8, 94.8, 94.7, 94.7, 94.8, 94.8, 94.8, 94.8, 94.8, 94.8, 94.8] },
          { name: 'Seattle', color: '#d97706', values: [94.6, 94.6, 94.6, 94.7, 94.7, 94.6, 94.6, 94.5, 94.6, 94.6, 94.6, 94.6] },
        ],
        goalReferencePct: 0.15,
      },
      donut: {
        title: 'Revenue by Product Line',
        slices: [
          { label: 'Coffee blends', value: 46, color: '#2563eb' },
          { label: 'Single origin', value: 22, color: '#059669' },
          { label: 'Cold brew', value: 14, color: '#d97706' },
          { label: 'Decaf', value: 10, color: '#7c3aed' },
          { label: 'Seasonal', value: 8, color: '#64748b' },
        ],
        centerValue: '$4.74M',
        centerSublabel: 'revenue / month',
      },
      horizontalBars: {
        title: 'Waste $ by SKU family (target $2K)',
        bars: [
          { label: 'Heritage Dark', value: 5.2 },
          { label: 'Morning Reserve', value: 3.8 },
          { label: 'Single Origin Eth.', value: 2.8 },
          { label: 'Cold Brew Conc.', value: 2.2 },
          { label: 'Decaf House', value: 1.4 },
        ],
        max: 8,
        goal: 2,
        unit: 'K',
        goalLabel: 'goal $2K',
      },
    },
    report: {
      category: 'Prism · Production',
      title: 'Weekly Production Yield Report · Week of Apr 21',
      dateLine: 'Generated by Prism on Apr 24, 2026 · Week of Apr 21 · Greenfield Roasting',
      status: 'Completed',
      summary: [
        'Weekly yield averaged 94.1% across 3 facilities (target 95%). Portland is the lowest at 92.8% — traced to shift-3 roast-profile drift.',
        'Weekly waste $18K (planned $14K). Coffee-blend line drove 68% of waste — concentrated in Heritage Dark and Morning Reserve.',
      ],
      chartTitle: 'Waste by cause ($K)',
      aging: [
        { label: 'Over-roast', value: 12, color: '#ef4444', display: '$12K' },
        { label: 'Ingredient var.', value: 3, color: '#f97316', display: '$3K' },
        { label: 'Packaging', value: 2, color: '#f59e0b', display: '$2K' },
        { label: 'Other', value: 1, color: '#fbbf24', display: '$1K' },
      ],
      findings: [
        { impact: 'High', body: 'Portland shift-3 roast profile drifted 8°F above spec — recipe-overroast pattern.' },
        { impact: 'Medium', body: 'Heritage Dark blend waste ran 2.8% vs 1.5% target; ingredient variance contributing.' },
        { impact: 'Low', body: 'Tacoma and Seattle performing in band; no action needed.' },
      ],
      recommendations: [
        'Re-calibrate Portland shift-3 roaster thermocouples (suspected drift).',
        'Review Heritage Dark recipe step-by-step with QA team.',
        'Maintain Tacoma/Seattle cadence.',
      ],
      footer: 'Generated by Prism · query cost $0.05 · sourced from Foundry warehouse',
    },
    metricTree: {
      eyebrow: 'Greenfield Roasting · Lens',
      title: 'Gross Margin → Drivers',
      rootLabel: 'Gross Margin',
      rootValue: '38.2%',
      subtitle: 'Yield × Price × Mix, broken down by facility and product line.',
    },
    map: {
      title: 'Distributor Heatmap · 42 distributors',
      windowLabel: 'Sell-through · Last 4 weeks',
      legendTitle: 'Velocity',
      legendItems: [
        { label: 'Above plan', color: '#10b981' },
        { label: 'On plan', color: '#3b82f6' },
        { label: 'Below plan', color: '#ef4444' },
        { label: 'Facility', color: '#64748b' },
      ],
    },
  },

  /* ---------------------------- Construction ---------------------------- */
  construction: {
    dashboard: {
      eyebrow: 'Pacific GC · Lens',
      title: 'Project Controls · All Active',
      kpis: [
        {
          label: 'Backlog',
          value: '$412M',
          trend: '+8%',
          trendGood: true,
          goal: '$400M',
          status: 'on-track',
          spark: [380, 384, 388, 392, 395, 398, 400, 404, 407, 410, 411, 412],
        },
        {
          label: 'CPI',
          value: '0.94',
          trend: '-0.03',
          trendGood: false,
          goal: '≥ 1.00',
          status: 'at-risk',
          spark: [0.98, 0.98, 0.97, 0.97, 0.96, 0.96, 0.95, 0.95, 0.95, 0.94, 0.94, 0.94],
        },
        {
          label: 'CO Backlog',
          value: '$682K',
          trend: '+3',
          trendGood: false,
          goal: '≤ $400K',
          status: 'off-track',
          spark: [420, 440, 460, 480, 520, 560, 600, 620, 640, 660, 680, 682],
        },
      ],
      line: {
        title: 'Weekly Earned-Value Variance · 12 weeks ($K)',
        series: [
          { name: 'EVA', color: '#2563eb', values: [-120, -180, -240, -320, -400, -480, -560, -640, -700, -760, -800, -820] },
          { name: 'CO recovery', color: '#10b981', values: [80, 120, 160, 200, 240, 280, 320, 360, 380, 400, 410, 420] },
        ],
        goalReferencePct: 0.5,
      },
      donut: {
        title: 'Revenue by Project Type',
        slices: [
          { label: 'Commercial', value: 36, color: '#2563eb' },
          { label: 'Medical', value: 26, color: '#059669' },
          { label: 'Hospitality', value: 18, color: '#d97706' },
          { label: 'Civic', value: 12, color: '#7c3aed' },
          { label: 'Industrial', value: 8, color: '#64748b' },
        ],
        centerValue: '$186M',
        centerSublabel: 'revenue / year',
      },
      horizontalBars: {
        title: 'Schedule Adherence by Sub (top 5, target 95%)',
        bars: [
          { label: 'Parker Mech', value: 98 },
          { label: 'Alpine Elec', value: 97 },
          { label: 'Ridge Insul', value: 92 },
          { label: 'Summit Str', value: 88 },
          { label: 'Cedar Str', value: 76 },
        ],
        max: 100,
        goal: 95,
        unit: '%',
        goalLabel: 'goal 95%',
      },
    },
    report: {
      category: 'Prism · Project Controls',
      title: 'Weekly Job Cost Report · Week of Apr 21',
      dateLine: 'Generated by Prism on Apr 24, 2026 · Week of Apr 21 · Pacific GC',
      status: 'Completed',
      summary: [
        'Portfolio earned-value variance -$820K (CPI 0.94). 5 of 40 active projects at risk of budget overrun; Parker Medical Tower (+$620K projected) is the largest.',
        'Change-order pipeline $682K pending owner signature across 11 COs. $420K is recoverable from cost overruns.',
      ],
      chartTitle: 'Projected overrun by driver ($K)',
      aging: [
        { label: 'Steel escalation', value: 320, color: '#ef4444', display: '$320K' },
        { label: 'Scope add', value: 240, color: '#f97316', display: '$240K' },
        { label: 'Productivity', value: 180, color: '#f59e0b', display: '$180K' },
        { label: 'Design delay', value: 140, color: '#fbbf24', display: '$140K' },
        { label: 'Other', value: 80, color: '#fde047', display: '$80K' },
      ],
      findings: [
        { impact: 'High', body: 'Parker Medical $240K CO for steel escalation fully documented — owner counsel review is the bottleneck.' },
        { impact: 'Medium', body: 'Cedar Park productivity gap traces to one subcontractor running 14 days behind schedule.' },
        { impact: 'Low', body: 'Horizon Industrial design-delay CO is routine; expect sign-off within 10 days.' },
      ],
      recommendations: [
        'PM-level escalation on Parker Medical CO this week.',
        'Subcontractor performance review at Cedar Park (replace vs re-plan).',
        'Pre-file Horizon CO via owner portal to reduce turnaround.',
      ],
      footer: 'Generated by Prism · query cost $0.07 · sourced from Foundry warehouse',
    },
    metricTree: {
      eyebrow: 'Pacific GC · Lens',
      title: 'Gross Margin → Drivers',
      rootLabel: 'Gross Margin',
      rootValue: '8.4%',
      subtitle: 'Direct Costs × Productivity × Change-Order Recovery, broken down by project and sub.',
    },
    map: {
      title: 'Active Jobsites · 40 projects',
      windowLabel: 'CPI · Live',
      legendTitle: 'Project status',
      legendItems: [
        { label: 'On track (CPI ≥ 1)', color: '#10b981' },
        { label: 'Monitoring', color: '#f59e0b' },
        { label: 'At risk (CPI < 0.9)', color: '#ef4444' },
        { label: 'Regional yard', color: '#3b82f6' },
      ],
    },
  },
};
